# Generated by Django 4.1 on 2022-08-09 19:29

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=50, unique=True, verbose_name='Case name')),
                ('active', models.BooleanField(default=True, verbose_name='Case display activity')),
                ('technology', models.CharField(blank=True, max_length=200, verbose_name='Case creation technologies')),
                ('text', models.TextField(blank=True, verbose_name='Case text')),
                ('img_bg', models.ImageField(blank=True, upload_to=portfolio.models.img_path, verbose_name='Case background image')),
                ('img_obj', models.ImageField(blank=True, upload_to=portfolio.models.img_path, verbose_name='Case image object')),
                ('img_bg_detail', models.ImageField(blank=True, upload_to=portfolio.models.img_path, verbose_name='Case background image for detail page')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Work display activity')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=50, verbose_name='Work name')),
                ('img', models.ImageField(blank=True, upload_to=portfolio.models.img_path, verbose_name='Work image')),
                ('text', models.TextField(blank=True, verbose_name='Work text')),
                ('link', models.CharField(blank=True, max_length=50, verbose_name='Work view link')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.case')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=portfolio.models.img_path, verbose_name='Additional work image')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.work', verbose_name='Work')),
            ],
        ),
    ]
